"""
dashboard_app.py
=============================================================================
QuantumAML Nexus -- Role-Based Interactive Forensic & Compliance Dashboard
=============================================================================
Author: Advanced AML AI Engineer
Purpose:
  1. Role-Based Access Control (RBAC):
     - Bank Compliance Officer View: Operational alert queue, regulatory threshold
       breaches, triage workflow (Open, Escalated, Approved, Cleared), 1-click export
       of FinCEN Form 111 SAR narratives.
     - Law Enforcement / Forensic Analyst View: Unrestricted cluster tracing, raw
       wallet/account graphs, multi-hop peeling chains, fiat & crypto telemetry.
  2. Interactive 2-Hop Network Graph Visualization:
     - Renders JSON data from GET /api/v1/investigate/{tx_id}/subgraph via PyVis.
     - Node color coding (focal source, focal target, cycle/mule nodes, neighbors).
     - Edge weightings scaled by transaction volume.
  3. Live Alert Feed & XAI Narrative Panel:
     - Real-time transaction stream with risk score progress bars.
     - TreeSHAP feature attributions (velocity spikes, structuring, crypto tumbling).
     - Automated plain-English SAR narratives generated by xai_explainer.py.
  4. API Integration & Action Handlers:
     - Connects directly to FastAPI backend (http://localhost:8000/api/v1/...).
     - Action buttons: Approve SAR, Escalate to LEO, Dismiss False Positive.
     - Standalone fallback mode if backend server is offline.
=============================================================================
"""

from __future__ import annotations
import json
import logging
import math
import os
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import requests
import streamlit as st
import streamlit.components.v1 as components

# Ensure root directory is in sys.path
ROOT_DIR = os.path.abspath(os.path.dirname(__file__))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from agent_engine import AMLAgent, agent_engine
from xai_explainer import AMLThreatExplainer, threat_explainer

try:
    import plotly.express as px
    import plotly.graph_objects as go
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False

try:
    from pyvis.network import Network
    HAS_PYVIS = True
except ImportError:
    HAS_PYVIS = False

DEFAULT_API_URL = os.environ.get("AML_API_URL", "http://localhost:8000")


# =============================================================================
# BACKEND API CLIENT & DATA PROCESSING HELPERS
# =============================================================================

def check_backend_health(base_url: str) -> Tuple[bool, Dict[str, Any]]:
    """Checks availability and model telemetry of the FastAPI server."""
    try:
        resp = requests.get(f"{base_url}/health", timeout=1.5)
        if resp.status_code == 200:
            return True, resp.json()
    except Exception:
        pass
    return False, {}


def fetch_all_alerts(base_url: str) -> List[Dict[str, Any]]:
    """Fetches alert list from backend API, or falls back to in-memory agent."""
    is_live, _ = check_backend_health(base_url)
    if is_live:
        try:
            resp = requests.get(f"{base_url}/api/v1/alerts", timeout=3.0)
            if resp.status_code == 200:
                return resp.json().get("alerts", [])
        except Exception:
            pass

    # Local fallback to in-memory agent
    items = []
    for tx_id, tx in reversed(list(agent_engine.transactions.items())):
        amount = tx.get("amount_usd", tx.get("amount", 0.0))
        items.append({
            "tx_id": tx_id,
            "risk_score": tx.get("aggregate_risk_score", tx.get("risk_score", 0.0)),
            "severity_tier": tx.get("severity_tier", "LOW_NOMINAL"),
            "alert_triggered": tx.get("alert_triggered", False),
            "triage_status": tx.get("triage_status", "OPEN"),
            "triage_note": tx.get("triage_note", ""),
            "source_node": tx.get("source_node", tx.get("account_from", "")),
            "target_node": tx.get("target_node", tx.get("account_to", "")),
            "amount_usd": amount,
            "amount": amount,
            "currency": tx.get("currency", "USD"),
            "rail": tx.get("rail", "fiat"),
            "reason_codes": tx.get("reason_codes", []),
            "timestamp": tx.get("timestamp", ""),
            "regulatory_breach": amount >= 10000.0 or tx.get("regulatory_breach", False),
            "audit_hash": tx.get("audit_hash", ""),
        })
    return items


def fetch_subgraph_data(base_url: str, tx_id: str) -> Dict[str, Any]:
    """Fetches 2-hop neighborhood from GET /api/v1/investigate/{tx_id}/subgraph."""
    is_live, _ = check_backend_health(base_url)
    if is_live:
        try:
            resp = requests.get(f"{base_url}/api/v1/investigate/{tx_id}/subgraph", timeout=3.0)
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass

    # Local in-process fallback
    return agent_engine.extract_2hop_subgraph(tx_id=tx_id)


def fetch_investigation_brief(base_url: str, tx_id: str) -> Dict[str, Any]:
    """Pulls full forensic brief from backend API, or generates via xai_explainer."""
    is_live, _ = check_backend_health(base_url)
    if is_live:
        try:
            resp = requests.get(f"{base_url}/api/v1/investigate/{tx_id}/brief", timeout=3.0)
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass

    # Local in-process fallback
    return threat_explainer.generate_investigation_brief(tx_id=tx_id)


def execute_triage_action(base_url: str, tx_id: str, action: str, note: str, role: str) -> bool:
    """Sends action update to backend API or updates in-memory agent."""
    is_live, _ = check_backend_health(base_url)
    if is_live:
        try:
            resp = requests.post(
                f"{base_url}/api/v1/alerts/{tx_id}/action",
                json={"action": action, "notes": note, "analyst_id": role},
                timeout=3.0,
            )
            if resp.status_code == 200:
                return True
        except Exception:
            pass

    # Local fallback
    try:
        agent_engine.update_triage_status(tx_id, action, note)
        return True
    except Exception:
        return False


def compute_kpis(alerts_data: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Computes aggregate operational and regulatory KPI metrics."""
    total = len(alerts_data)
    open_count = sum(1 for a in alerts_data if a.get("triage_status") in ("OPEN", "PENDING"))
    escalated = sum(1 for a in alerts_data if a.get("triage_status") in ("ESCALATED", "ESCALATED_LEO"))
    approved = sum(1 for a in alerts_data if a.get("triage_status") in ("APPROVED", "APPROVED_SAR"))
    cleared = sum(1 for a in alerts_data if a.get("triage_status") in ("CLEARED", "CLEARED_FALSE_POSITIVE", "DISMISSED"))
    breaches = sum(
        1 for a in alerts_data
        if a.get("regulatory_breach") or a.get("amount_usd", 0.0) >= 10000.0 or a.get("amount", 0.0) >= 10000.0
    )
    scores = [a.get("risk_score", 0.0) for a in alerts_data if "risk_score" in a]
    avg_risk = round(sum(scores) / len(scores), 1) if scores else 0.0

    return {
        "total": total,
        "open": open_count,
        "escalated": escalated,
        "approved": approved,
        "cleared": cleared,
        "breaches": breaches,
        "avg_risk": avg_risk,
    }


def seed_synthetic_activity():
    """Seeds rich synthetic transaction scenarios into the agent engine."""
    # 1. Normal Wire
    agent_engine.evaluate({
        "tx_id": "TX_FEDWIRE_101",
        "account_from": "CORP_SUPPLY_INC",
        "account_to": "LOGISTICS_PARTNER_LLC",
        "amount": 4200.0,
        "currency": "USD",
    })

    # 2. Directed Cycle: A -> B -> C -> A (Circular Layering)
    agent_engine.evaluate({"tx_id": "TX_CYCLE_01", "account_from": "ACC_SHELL_ALPHA", "account_to": "ACC_MULE_BETA", "amount": 65000.0})
    agent_engine.evaluate({"tx_id": "TX_CYCLE_02", "account_from": "ACC_MULE_BETA", "account_to": "ACC_OFFSHORE_GAMMA", "amount": 64200.0})
    agent_engine.evaluate({"tx_id": "TX_CYCLE_03", "account_from": "ACC_OFFSHORE_GAMMA", "account_to": "ACC_SHELL_ALPHA", "amount": 63800.0})

    # 3. Smurfing / Structuring Ring (Evasion around $9,500)
    for i in range(4):
        agent_engine.evaluate({
            "tx_id": f"TX_SMURF_FEED_{i:02d}",
            "account_from": f"ACC_MULE_STRUCT_{i:02d}",
            "account_to": "ACC_AGGREGATOR_KINGPIN",
            "amount": 9500.0,
            "currency": "USD",
        })

    # 4. Crypto Peeling Chain & Mixer Interaction
    agent_engine.evaluate({
        "tx_hash": "0x7e29a4b801c109df",
        "from_wallet": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        "to_wallet": "3MixerTumblingService99",
        "amount": 12.8,
        "currency": "BTC",
        "mixer_risk": True,
        "is_peeling_chain": True,
        "hop_count": 5,
    })


def render_network_graph(
    subgraph_data: Dict[str, Any],
    focal_src: str,
    focal_dst: str,
    highlighted_cycle_nodes: Optional[List[str]] = None,
) -> str:
    """
    Renders the 2-hop neighborhood network data from GET /api/v1/investigate/{tx_id}/subgraph
    using PyVis with custom styling, distinct color coding, and volume-weighted edges.
    """
    if not HAS_PYVIS:
        return ""

    net = Network(
        height="520px",
        width="100%",
        bgcolor="#090d16",
        font_color="#f1f5f9",
        directed=True,
    )
    net.barnes_hut(gravity=-2500, central_gravity=0.3, spring_length=160, damping=0.9)

    cycle_set = set(highlighted_cycle_nodes or [])
    nodes = subgraph_data.get("nodes", [])
    edges = subgraph_data.get("edges", [])

    for node in nodes:
        nid = node.get("id") or str(node)
        in_deg = node.get("in_degree", 0)
        out_deg = node.get("out_degree", 0)
        flow_bal = node.get("flow_balance", 0.0)

        is_src = (nid == focal_src)
        is_dst = (nid == focal_dst)
        in_cycle = (nid in cycle_set) or (in_deg > 0 and out_deg > 0 and abs(flow_bal) < 200.0 and in_deg + out_deg >= 2)

        if is_src:
            color = "#f97316"  # Orange: Focal Originator
            size = 32
            shape = "dot"
            role_desc = "FOCAL ORIGINATOR"
        elif is_dst:
            color = "#ef4444"  # Red: Focal Beneficiary
            size = 32
            shape = "dot"
            role_desc = "FOCAL BENEFICIARY"
        elif in_cycle:
            color = "#a855f7"  # Purple: Cycle / Intermediary Mule
            size = 26
            shape = "diamond"
            role_desc = "INTERMEDIARY MULE / CYCLE NODE"
        else:
            color = "#3b82f6"  # Blue: Neighbor Entity
            size = 18
            shape = "dot"
            role_desc = "NEIGHBOR ENTITY"

        net.add_node(
            nid,
            label=f"{nid}\n[{role_desc.split()[0]}]",
            color=color,
            size=size,
            shape=shape,
            title=(
                f"<b>Entity ID:</b> {nid}<br>"
                f"<b>Role:</b> {role_desc}<br>"
                f"<b>In-Degree:</b> {in_deg} | <b>Out-Degree:</b> {out_deg}<br>"
                f"<b>Net Flow Balance:</b> ${flow_bal:,.2f}"
            ),
        )

    for edge in edges:
        u = edge.get("source")
        v = edge.get("target")
        amt = float(edge.get("amount", edge.get("amount_usd", 1000.0)))
        curr = edge.get("currency", "USD")
        rail = edge.get("rail", "fiat")
        is_focal = edge.get("is_focal", False) or (u == focal_src and v == focal_dst)
        is_cycle_edge = (u in cycle_set and v in cycle_set)

        # Edge weighting based on transaction volume
        edge_weight = max(1, min(10, int(amt / 8000) + 1))

        if is_focal:
            edge_color = "#ef4444"  # Red for focal transfer
            edge_weight = max(3, edge_weight)
        elif is_cycle_edge:
            edge_color = "#a855f7"  # Purple for cycle flow
            edge_weight = max(2, edge_weight)
        else:
            edge_color = "#475569"  # Slate for normal flow

        net.add_edge(
            u,
            v,
            label=f"${amt:,.0f}" if amt < 1e6 else f"${amt/1e6:.1f}M",
            color=edge_color,
            width=edge_weight,
            title=(
                f"<b>Transfer:</b> {u} ➔ {v}<br>"
                f"<b>Amount:</b> ${amt:,.2f} {curr}<br>"
                f"<b>Rail:</b> {rail.upper()}<br>"
                f"<b>Weight:</b> {edge_weight}px"
            ),
        )

    return net.generate_html()


# =============================================================================
# STREAMLIT UI APPLICATION
# =============================================================================

def main():
    st.set_page_config(
        page_title="QuantumAML Nexus | Forensic Intelligence Portal",
        page_icon="🛡️",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    # Custom High-End Styling
    st.markdown("""
    <style>
        .stApp {
            background-color: #090d16;
            color: #f1f5f9;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }
        .main-header {
            background: linear-gradient(135deg, rgba(30, 41, 59, 0.7) 0%, rgba(15, 23, 42, 0.9) 100%);
            border: 1px solid rgba(255, 255, 255, 0.08);
            border-radius: 12px;
            padding: 20px 24px;
            margin-bottom: 24px;
            box-shadow: 0 4px 20px -2px rgba(0, 0, 0, 0.5);
        }
        .metric-card {
            background: rgba(30, 41, 59, 0.5);
            border: 1px solid rgba(255, 255, 255, 0.08);
            border-radius: 10px;
            padding: 16px;
            text-align: center;
            transition: transform 0.2s ease, border-color 0.2s ease;
        }
        .metric-card:hover {
            transform: translateY(-2px);
            border-color: rgba(59, 130, 246, 0.5);
        }
        .metric-val {
            font-size: 26px;
            font-weight: 700;
            margin-top: 4px;
        }
        .badge-critical {
            background-color: rgba(239, 68, 68, 0.2);
            color: #f87171;
            border: 1px solid #ef4444;
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 12px;
            font-weight: 600;
        }
        .badge-open {
            background-color: rgba(59, 130, 246, 0.2);
            color: #60a5fa;
            border: 1px solid #3b82f6;
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 11px;
        }
    </style>
    """, unsafe_allow_html=True)

    # Ensure baseline synthetic activity exists if agent memory is clean
    if len(agent_engine.transactions) == 0:
        seed_synthetic_activity()

    # Sidebar: Role switcher & API connection
    with st.sidebar:
        st.markdown("## 🛡️ QuantumAML Nexus")
        st.caption("Enterprise Financial Crime AI Agent Platform")
        st.markdown("---")

        st.markdown("### 👤 User Persona & Role")
        selected_role = st.radio(
            "Select Active Role:",
            [
                "Bank Compliance Officer",
                "Law Enforcement / Forensic Analyst",
            ],
            index=0,
            help="Enforces role-based views and separation of duties (SoD).",
        )

        st.markdown("---")
        st.markdown("### 🔌 API Connection Settings")
        api_url = st.text_input("FastAPI Backend URL:", value=DEFAULT_API_URL)
        is_live, health_data = check_backend_health(api_url)

        if is_live:
            st.success(f"Backend Connected: `{api_url}` ✅")
            st.caption(f"Service: {health_data.get('service')} v{health_data.get('version')}")
        else:
            st.warning(f"FastAPI Offline (`{api_url}`). Running in Standalone In-Process Mode ⚡")

        st.markdown("---")
        if st.button("🔄 Inject Fresh Simulated Stream", use_container_width=True):
            seed_synthetic_activity()
            st.toast("Injected new multi-rail transaction burst into agent!", icon="⚡")
            st.rerun()

    # Load alert dataset
    alerts_data = fetch_all_alerts(api_url)
    kpis = compute_kpis(alerts_data)

    # Header banner
    st.markdown(f"""
    <div class="main-header">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
                <h1 style="margin: 0; font-size: 26px; font-weight: 700; color: #f8fafc;">
                    🛡️ QuantumAML Nexus: Investigator Operations Center
                </h1>
                <p style="margin: 4px 0 0 0; color: #94a3b8; font-size: 14px;">
                    Active Role: <strong style="color: #60a5fa;">{selected_role}</strong> | 
                    GNN Topology: <span style="color: #34d399;">Inductive GraphSAGE</span> | 
                    Temporal Classifier: <span style="color: #34d399;">LightGBM EWMA</span>
                </p>
            </div>
            <div style="text-align: right;">
                <span class="badge-critical">Alert Threshold T*: 75.0</span>
                <span class="badge-open">Live Stream Active</span>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # KPI Summary Cards
    kpi_c1, kpi_c2, kpi_c3, kpi_c4, kpi_c5 = st.columns(5)
    with kpi_c1:
        st.markdown(f"""<div class="metric-card"><div style="color: #94a3b8; font-size: 12px;">TOTAL EVALUATED</div><div class="metric-val" style="color: #f1f5f9;">{kpis['total']}</div></div>""", unsafe_allow_html=True)
    with kpi_c2:
        st.markdown(f"""<div class="metric-card"><div style="color: #60a5fa; font-size: 12px;">OPEN TRIAGE</div><div class="metric-val" style="color: #60a5fa;">{kpis['open']}</div></div>""", unsafe_allow_html=True)
    with kpi_c3:
        st.markdown(f"""<div class="metric-card"><div style="color: #c084fc; font-size: 12px;">ESCALATED LEO</div><div class="metric-val" style="color: #c084fc;">{kpis['escalated']}</div></div>""", unsafe_allow_html=True)
    with kpi_c4:
        st.markdown(f"""<div class="metric-card"><div style="color: #34d399; font-size: 12px;">APPROVED SARS</div><div class="metric-val" style="color: #34d399;">{kpis['approved']}</div></div>""", unsafe_allow_html=True)
    with kpi_c5:
        st.markdown(f"""<div class="metric-card"><div style="color: #f87171; font-size: 12px;">THRESHOLD BREACHES</div><div class="metric-val" style="color: #f87171;">{kpis['breaches']}</div></div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # =========================================================================
    # LIVE ALERT FEED & TRIAGE QUEUE
    # =========================================================================
    st.markdown("### 📋 Live Transaction Stream & Regulatory Alert Feed")

    col_f1, col_f2, col_f3 = st.columns([2, 2, 2])
    with col_f1:
        triage_filter = st.selectbox(
            "Filter Triage Status:",
            ["All Alerts", "OPEN", "ESCALATED", "ESCALATED_LEO", "APPROVED", "APPROVED_SAR", "CLEARED", "CLEARED_FALSE_POSITIVE"],
            index=0,
        )
    with col_f2:
        rail_filter = st.selectbox("Financial Rail:", ["All Rails", "fiat", "crypto"])
    with col_f3:
        min_score = st.slider("Min Risk Score Threshold:", 0.0, 100.0, 0.0, step=5.0)

    # Filter alerts
    filtered_alerts = alerts_data
    if triage_filter != "All Alerts":
        filtered_alerts = [a for a in filtered_alerts if a.get("triage_status") == triage_filter]
    if rail_filter != "All Rails":
        filtered_alerts = [a for a in filtered_alerts if a.get("rail") == rail_filter]
    if min_score > 0:
        filtered_alerts = [a for a in filtered_alerts if a.get("risk_score", 0.0) >= min_score]

    # In Bank Compliance Officer role, prioritize high risk and regulatory threshold breaches
    if selected_role == "Bank Compliance Officer":
        st.caption("🔒 Compliance View: Filtered view prioritizing regulatory threshold breaches (≥$10k) and operational triage queues.")

    if not filtered_alerts:
        st.info("No transactions match the selected criteria.")
    else:
        df_rows = []
        for a in filtered_alerts:
            amt = a.get("amount_usd", a.get("amount", 0.0))
            df_rows.append({
                "Transaction ID": a["tx_id"],
                "Risk Score": a["risk_score"],
                "Severity Tier": a.get("severity_tier", "LOW_NOMINAL"),
                "Triage Status": a.get("triage_status", "OPEN"),
                "Rail": a.get("rail", "fiat").upper(),
                "Amount (USD)": amt,
                "Origin": a.get("source_node", ""),
                "Beneficiary": a.get("target_node", ""),
                "Fired Rules": ", ".join(a.get("reason_codes", [])) or "NOMINAL_CLEAR",
            })
        df_display = pd.DataFrame(df_rows)

        st.dataframe(
            df_display,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Risk Score": st.column_config.ProgressColumn(
                    "Risk Score (0-100)",
                    min_value=0.0,
                    max_value=100.0,
                    format="%.1f",
                ),
                "Amount (USD)": st.column_config.NumberColumn(
                    "Amount",
                    format="$%d",
                ),
            },
        )

    st.markdown("---")

    # =========================================================================
    # ACTIVE INVESTIGATION SELECTION & WORKSPACE
    # =========================================================================
    st.markdown("### 🔎 Forensic Investigation & Case Review Workspace")

    alert_ids = [a["tx_id"] for a in filtered_alerts] if filtered_alerts else [a["tx_id"] for a in alerts_data]
    selected_tx_id = st.selectbox(
        "Select Flagged Transaction ID to Inspect:",
        options=alert_ids,
        index=0 if alert_ids else None,
    )

    if selected_tx_id:
        with st.spinner(f"Extracting 2-hop topological subgraph and TreeSHAP weights for {selected_tx_id}..."):
            brief = fetch_investigation_brief(api_url, selected_tx_id)
            subgraph_json = fetch_subgraph_data(api_url, selected_tx_id)

        focal_src = brief["focal_entities"]["source"]
        focal_dst = brief["focal_entities"]["target"]
        score = brief["composite_risk_score"]
        typology = brief["primary_typology"]
        tier = brief["threat_tier"]

        # =====================================================================
        # ROLE VIEW 1: BANK COMPLIANCE OFFICER VIEW
        # =====================================================================
        if selected_role == "Bank Compliance Officer":
            st.markdown(f"#### 🏛️ Compliance Officer Alert Queue: `{selected_tx_id}`")

            c_meta1, c_meta2, c_meta3 = st.columns(3)
            with c_meta1:
                st.markdown(f"**Origin Account:** `{focal_src}`")
                st.markdown(f"**Beneficiary Account:** `{focal_dst}`")
            with c_meta2:
                st.markdown(f"**Primary Typology:** `{typology}`")
                st.markdown(f"**Composite Risk Score:** `{score:.1f} / 100`")
            with c_meta3:
                st.markdown(f"**BSA/FinCEN Breach (≥$10k):** `{'YES ⚠️' if brief['transaction_details']['amount'] >= 10000.0 else 'NO'}`")
                st.markdown(f"**Filing Requirement:** `{'Mandatory SAR Form 111' if score >= 75.0 else 'Standard Monitoring'}`")

            # Action Buttons Panel
            st.markdown("##### ⚡ Operational Action Handlers")
            col_act1, col_act2, col_act3 = st.columns(3)

            with col_act1:
                if st.button("✅ Approve Automated SAR Filing", use_container_width=True):
                    ok = execute_triage_action(api_url, selected_tx_id, "APPROVE", "Approved by Compliance Officer for Form 111 filing.", selected_role)
                    if ok:
                        st.success("Alert status updated to APPROVED_SAR ✅")
                        st.rerun()

            with col_act2:
                if st.button("🚨 Escalate to Law Enforcement / FIU", use_container_width=True):
                    ok = execute_triage_action(api_url, selected_tx_id, "ESCALATE", "Escalated for immediate asset freezing inquiry.", selected_role)
                    if ok:
                        st.warning("Alert status updated to ESCALATED_LEO 🚨")
                        st.rerun()

            with col_act3:
                if st.button("🛡️ Dismiss False Positive", use_container_width=True):
                    ok = execute_triage_action(api_url, selected_tx_id, "DISMISS", "Verified legitimate commercial wire transfer.", selected_role)
                    if ok:
                        st.info("Alert status updated to CLEARED_FALSE_POSITIVE 🛡️")
                        st.rerun()

            # 1-Click SAR Export
            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown("##### 📄 1-Click Export: FinCEN Form 111 Regulatory SAR Narrative")
            sar_text = brief.get("plain_text_narrative", "")
            st.text_area("SAR Narrative Preview:", value=sar_text, height=220)

            col_dl1, col_dl2 = st.columns(2)
            with col_dl1:
                st.download_button(
                    label="📥 1-Click Export SAR Narrative (.TXT)",
                    data=sar_text,
                    file_name=f"FinCEN_SAR_Narrative_{selected_tx_id}.txt",
                    mime="text/plain",
                    use_container_width=True,
                )
            with col_dl2:
                st.download_button(
                    label="📥 Export Full Audit Dossier (.JSON)",
                    data=json.dumps(brief, indent=2),
                    file_name=f"AML_Dossier_{selected_tx_id}.json",
                    mime="application/json",
                    use_container_width=True,
                )

        # =====================================================================
        # ROLE VIEW 2: LAW ENFORCEMENT / FORENSIC ANALYST VIEW
        # =====================================================================
        else:
            st.markdown(f"#### 🕵️ Forensic Analyst Deep-Dive & Cluster Portal: `{selected_tx_id}`")

            col_d1, col_d2, col_d3 = st.columns(3)
            with col_d1:
                st.markdown(f"**Focal Path:** `{focal_src} ➔ {focal_dst}`")
                st.markdown(f"**Detected Typology:** `{typology}`")
            with col_d2:
                st.markdown(f"**Cycles in 2-Hop:** `{brief['structural_metrics'].get('cycle_count', 0)} detected`")
                st.markdown(f"**Pass-Through Flow Equality:** `{brief['structural_metrics'].get('pass_through_equality', 0.0):.1%}`")
            with col_d3:
                st.markdown(f"**Multi-Hop Peeling Chains:** `{'FLAGGED ⚠️' if 'PEELING_CHAIN' in str(brief) or 'CHAIN' in typology else 'NOMINAL'}`")
                st.markdown(f"**Evidence SHA-256 Digest:** `{brief.get('audit_hash', '')[:20]}...`")

            # LEO Action Panel
            col_leo1, col_leo2 = st.columns(2)
            with col_leo1:
                if st.button("🚨 Issue Emergency Asset Freeze Notice (31 U.S.C. § 5318A)", use_container_width=True):
                    ok = execute_triage_action(api_url, selected_tx_id, "ESCALATE", "Subpoena notice issued under 31 U.S.C. § 5318A.", selected_role)
                    if ok:
                        st.success("Asset Freeze Notice dispatched to clearing nodes! 🚨")
                        st.rerun()
            with col_leo2:
                if st.button("📁 Mark Case SEALED & Cryptographically Locked", use_container_width=True):
                    ok = execute_triage_action(api_url, selected_tx_id, "APPROVED_SAR", "Sealed evidence locker archived for prosecution.", selected_role)
                    if ok:
                        st.info("Case dossier cryptographically locked. 📁")
                        st.rerun()

        # =====================================================================
        # COMMON PANELS: INTERACTIVE 2-HOP NETWORK GRAPH & XAI NARRATIVE
        # =====================================================================
        st.markdown("---")
        vis_tab, shap_tab, narrative_tab = st.tabs([
            "🕸️ Interactive 2-Hop Network Graph (Vis.js / PyVis)",
            "📊 TreeSHAP Feature Attributions & Spikes",
            "📜 Automated Plain-English SAR Narrative",
        ])

        with vis_tab:
            st.markdown("##### Interactive 2-Hop Neighborhood Visualization")
            st.caption(
                "Renders GET /api/v1/investigate/{tx_id}/subgraph. "
                "Color coding: 🟧 Focal Source | 🟥 Focal Beneficiary | 🟪 Cycles / Mule Accounts | 🟦 Benign Entities. "
                "Edge thickness is weighted by transaction volume."
            )

            cycle_nodes = brief.get("highlighted_graph_path", {}).get("node_ids", [])
            graph_html = render_network_graph(subgraph_json, focal_src, focal_dst, cycle_nodes)

            if graph_html:
                components.html(graph_html, height=530, scrolling=False)
            else:
                st.warning("PyVis graph rendering unavailable. Displaying raw subgraph JSON:")
                st.json(subgraph_json)

        with shap_tab:
            st.markdown("##### TreeSHAP Feature Importance & Attribution Breakdown")
            attributions = brief.get("key_risk_factors", [])

            if attributions:
                df_shap = pd.DataFrame(attributions)

                if HAS_PLOTLY:
                    fig_shap = px.bar(
                        df_shap,
                        x="contribution_percentage",
                        y="display_name",
                        orientation="h",
                        color="direction",
                        color_discrete_map={
                            "RISK_INCREASING": "#ef4444",
                            "RISK_DECREASING": "#10b981",
                        },
                        text="contribution_percentage",
                        title="TreeSHAP Feature Contributions (%) Driving Risk Score",
                    )
                    fig_shap.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
                    fig_shap.update_layout(
                        yaxis=dict(autorange="reversed"),
                        paper_bgcolor="rgba(15, 23, 42, 0.6)",
                        plot_bgcolor="rgba(15, 23, 42, 0.4)",
                        font=dict(color="#f1f5f9"),
                        height=360,
                        margin=dict(l=20, r=40, t=40, b=20),
                    )
                    st.plotly_chart(fig_shap, use_container_width=True)
                else:
                    st.dataframe(df_shap[["display_name", "contribution_percentage", "direction", "description"]])

                st.markdown("##### Top Explanatory Drivers")
                for factor in attributions[:4]:
                    st.markdown(
                        f"• **{factor['display_name']}** ({factor['contribution_percentage']:.1f}% contribution): "
                        f"`{factor['description']}`"
                    )

        with narrative_tab:
            st.markdown("##### Automated SAR Narrative (Generated by xai_explainer.py)")
            st.code(brief.get("plain_text_narrative", ""), language="text")

    # Footer
    st.markdown("---")
    st.caption(
        "QuantumAML Nexus v3.0 | Real-Time Multi-Tier AI Agent Dashboard | "
        "FinCEN 31 CFR § 1020.320 & FATF Travel Rule Operational Compliance Engine"
    )


if __name__ == "__main__":
    main()
